### PR TITLE
Fix #187: Preflight fee-token balance check before create order

### LINKED ISSUE #187: Create order should check for fee token balance
If the user does not have enough of the fee token (like USDC) to create the order, the "Submit create order" step fails. We should not even be submitting the tx if there is not enough balance to cover the create order fee. When the user clicks the "Create Order" button the UI should check if the fee token balance is sufficient. Note that if the user is also selling the fee token, check if the balance is sufficient after deducting the sell amount. Show an error modal before starting the process to submit the tx if the fee token balance is insufficient.

### PR DESCRIPTION
**Pull request by Texaglo**
## Summary
- add preflight fee-token balance validation in `CreateOrder.handleCreateOrder`
- block submission before checklist/tx when fee token balance is insufficient
- handle case where sell token equals fee token by requiring sell amount + fee amount

## Scope
- initial implementation commit only (tests and refinements follow in review cycle)

Refs #187

### CODE REVIEW

**Comment by Texaglo** [comment]
Initial code review findings on first push:

1. Missing targeted tests for new preflight behavior
- Need unit coverage for:
  - insufficient fee token balance blocks create-order tx before submission
  - sell-token == fee-token path requires sell amount + fee amount

2. Error-message numeric formatting risk
- Current message formatting casts potentially large decimal strings with `Number(...)`.
- This can lose precision or show scientific notation for extreme values.
- Recommend preserving the original decimal string formatting (or using existing formatting helpers) for balance/required lines in error copy.

I will push fixes for both in the next commit.

**Comment by Texaglo** [comment]
Follow-up review on push #2 (`e956a05`) found one remaining gap:
- If fee config is still loading, preflight should fail closed (not skip).

Addressed in push #3 (`840fc6c`) by requiring loaded fee config before proceeding.

**Comment by Texaglo** [comment]
Final post-fix code review (including vulnerability pass):

Status: ✅ PASS

What landed across 3 pushes:
1. Initial implementation: preflight fee-token balance check before submit/create tx.
2. Review-driven additions: targeted tests + safe amount-string formatting for error copy.
3. Final fix: fail closed when fee config is not yet loaded.

Validation:
- `npx vitest run`
- Result: `41/41` test files passed, `161/161` tests passed

Security/vulnerability pass for this change set:
- No new user-controlled HTML/script insertion paths
- No new external fetches/network surfaces added
- No credential/secret handling introduced
- Balance checks are local preflight guards only and do not alter tx payload semantics

No remaining blocking issues found in scope.

File: js/components/CreateOrder.js [hunk 1]
```diff
@@ -1666,6 +1677,56 @@ export class CreateOrder extends BaseComponent {
...
+        const feeTokenSymbol = refreshedFeeToken.symbol || 'fee token';
+        const availableFeeTokenWei = ethers.utils.parseUnits(
+            refreshedFeeToken.balance || '0',
+            feeTokenDecimals
+        );
+        const feeAmountWei = ethers.BigNumber.from(refreshedFeeToken.amount);
+
+        let sellAmountWeiForFeeToken = ethers.constants.Zero;
+        if (sameTokenForSellAndFee) {
+            const sellTokenDecimals = Number.isInteger(this.sellToken?.decimals)
```
Comment (dnlbui) [inline js/components/CreateOrder.js]: When the fee token is also the sell token, this path trusts the cached sell-token decimals. That cache is populated with token.decimals || 18 in handleTokenSelect(), so a valid 0-decimal ERC20 is stored as 18 and never falls back to getTokenDecimals(). In that case the preflight overstates the combined requirement and can falsely block a valid order even though the later transaction path uses the correct on-chain decimals.

File: js/components/CreateOrder.js [hunk 2]
```diff
@@ -1666,6 +1677,56 @@ export class CreateOrder extends BaseComponent {
         this.updateCreateButtonState();
     }
 
+    async validateFeeTokenBalanceBeforeSubmit(sellAmount) {
+        if (!this.feeToken?.address || !this.feeToken?.amount) {
+            throw new Error('Order creation fee data is still loading');
```
Comment (dnlbui) [inline js/components/CreateOrder.js:1703]: On a fresh tab load or right after a fee-config update, the button can still be enabled before the background fee config or balance refresh finishes. In that window this new preflight throws a loading error, so a valid order is rejected only because the user clicked before the async reads completed. The button state should block submit until this prerequisite is ready, or this path should await the initial load instead of treating it as an error.

**Comment by Texaglo** [comment]
Addressed both latest team review comments in commit `3fa7ef2`.

What changed:
- Fixed same-token fee preflight decimal handling so it no longer trusts a potentially stale cached sell-token decimal; when sell token == fee token, preflight now uses fee-token decimals directly.
- Added `ensureFeeTokenReadyForSubmit()` so preflight waits for fee-config and in-flight fee-balance loading instead of rejecting valid submits during startup/config-refresh timing windows.
- Updated token selection to preserve valid `0` decimals (`this.getTokenInputDecimals(token) ?? 18`) instead of coercing `0` to `18`.

Validation:
- `npx vitest run tests/createOrder.feeBalancePreflight.test.js` (5/5 passed)
- `npx vitest run` (41/41 files, 163/163 tests passed)

File: js/components/CreateOrder.js (hunk 1 above)
Comment (Texaglo) [reply js/components/CreateOrder.js]: Addressed in `3fa7ef2`.

Fix details:
- Same-token fee preflight now uses `feeTokenDecimals` directly for sell amount parsing.
- `handleTokenSelect` now preserves valid zero decimals via `this.getTokenInputDecimals(token) ?? 18` (instead of `token.decimals || 18`).

Added regression test: `uses fee-token decimals for same-token preflight even if sell token cache is stale` in `tests/createOrder.feeBalancePreflight.test.js`.

File: js/components/CreateOrder.js (hunk 2 above)
Comment (Texaglo) [reply js/components/CreateOrder.js:1703]: Addressed in `3fa7ef2`.

Fix details:
- Added `ensureFeeTokenReadyForSubmit()` to wait for fee config and in-flight fee balance loads before validation.
- Preflight now avoids transient "loading" rejects caused by startup/config-refresh races.

Added regression test: `waits for in-flight fee balance loading before evaluating preflight` in `tests/createOrder.feeBalancePreflight.test.js`.

File: js/components/CreateOrder.js [hunk 3]
```diff
@@ -1666,6 +1677,70 @@ export class CreateOrder extends BaseComponent {
...
+
+        const feeTokenAddress = String(refreshedFeeToken.address || '').toLowerCase();
+        const sellTokenAddress = String(this.sellToken?.address || '').toLowerCase();
+        const sameTokenForSellAndFee = feeTokenAddress && sellTokenAddress && feeTokenAddress === sellTokenAddress;
+
+        const feeTokenDecimals = Number.isInteger(refreshedFeeToken.decimals)
+            ? refreshedFeeToken.decimals
+            : 18;
+        const feeTokenSymbol = refreshedFeeToken.symbol || 'fee token';
+        const availableFeeTokenWei = ethers.utils.parseUnits(
```
Comment (dnlbui) [inline js/components/CreateOrder.js:1737]: If the fee-balance refresh falls back after a transient RPC failure or rate limit, `getTokenBalanceInfo()` returns `balance: 0` rather than signaling that the lookup failed. This path then parses that fallback as the maker fee-token balance, so a user who actually has enough funds can still be blocked with the "Insufficient ... balance" error purely because the balance refresh failed. The preflight should distinguish an actual zero balance from a balance lookup failure that should be retried.
